### PR TITLE
bgrabow soln d09 & d10

### PR DESCRIPTION
**Pull request by bgrabow**

### CODE REVIEW

**Comment by borkdude** [comment]
@bgrabow I made a small change to the test-diff script. I was surprised the test status is marked as success by CircleCI while an exception happened. Can you merge with the latest commits in master and update this PR to test (without removing the exception)?

**Comment by bgrabow** [comment]
Same exception, CI still passes.

**Comment by bgrabow** [comment]
I assume CI will skip my test case if they run slow? My day-9 clj ArrayDeque solution is pretty quick but I don't have a quick solution for cljs. If a slow test isn't going to be a problem then I will just upload the slow version. What do you suggest?

**Comment by borkdude** [comment]
@bgrabow See the notes on metadata here: https://github.com/borkdude/advent-of-cljc/#tests

**Comment by bgrabow** [comment]
Fixed the cljs compilation errors and skipped the cljs tests, thanks for the direction. CI build success is real this time!

**Comment by borkdude** [comment]
@bgrabow Can you please remove your own (test+real) input from the solution?

https://github.com/borkdude/advent-of-cljc/pull/94/files#diff-470aa1f881362bafb057de3f54b1c372R12

See the README and also this issue:

https://github.com/borkdude/advent-of-cljc/issues/6

I believe @mfikes found a nice solution by not giving away any hints in his code about the message in day 10 by hashing the string. Could be nice to apply here as well.

**Comment by bgrabow** [comment]
Removed the two input strings. Give me a little time to figure out how to remove the letter patterns.

**Comment by bgrabow** [comment]
Removed the letter patterns. Thanks for the hash suggestion, and sorry for committing the input in the first place!

**Pull request merged**
