### PR TITLE
Functioning in CLJ and buggy in CLJS

### PR DESCRIPTION
**Pull request by ClashTheBunny**
I assume I've found a bug in loom?
```
WARNING: cljs.core/bit-or, all arguments must be numbers, got [any Long] instead at line 494 cljs-test-runner-out/loom/alg_generic.cljc
```

This would also add loom as a dependency.  It's cljc, so it should normally be fine, but I doubt you want to have a bunch of libraries in this?

### CODE REVIEW

**Comment by borkdude** [comment]
This is only a warning. The tests fail because of:

Testing aoc.y2018.d07.ClashTheBunny
part-1 took 21.00 msecs

FAIL in (part-2) (cljs_test_runner.gen.js:1045:284)
expected: (= (str answer-2) (str (:timer (solve-2 input 5 60))))
  actual: (not (= "891" "732"))
part-2 took 154.00 msecs

**Comment by borkdude** [comment]
It seems you're not really using loom in the code? Why add it as a dep?

**Comment by ClashTheBunny** [comment]
I took your suggestion and wrote my own graph creation and manipulation functions:
```
+(defn remove-node-from-map-of-sets [nodes]
+  (comp (partial into {})
+        (partial map #(vector (first %) (apply disj (second %) nodes)))
+        (partial filter (comp (partial (comp not contains?) nodes) first))))
+
+(defn remove-node [graph & nodes]
+  (let [nodes (into #{} nodes)]
+   (-> graph
+    (update :nodeset #(apply disj % nodes))
+    (update :in (remove-node-from-map-of-sets nodes))
+    (update :adj (remove-node-from-map-of-sets nodes)))))
+
+(defn digraph [g & edges]
+   (reduce
+      (fn [g [n1 n2]]
+        (-> g
+            (update-in [:nodeset] (fnil conj #{}) n1 n2)
+            (update-in [:adj n1] (fnil conj #{}) n2)
+            (update-in [:in n2] (fnil conj #{}) n1)))
+      g edges))
```

I also figured out the cljs compatibility issues I was having.  Quite frustrating but now fixed and @mfikes filed a bug for one of the issues!

**Comment by ClashTheBunny** [comment]
Yay!  Everything passes and is fast!

**Pull request merged**
