### PR TITLE
2018/01-05/genmeblog

### PR DESCRIPTION
**Pull request by genmeblog**
I've added two new aliases for deps.edn to enable Cider/Emacs integration

### CODE REVIEW

**Comment by borkdude** [comment]
Another comment:

What if people are using different cider-nrepl versions? I think this is a nice addition to deps.edn buy maybe belongs in `~/.clojure/deps.edn`? Maybe add to the README instead of deps.edn?

**Comment by genmeblog** [comment]
Sorry for names, I don't know why I haven't noticed this in the description.
deps.edn reverted - you're right, such config can be made locally.

**Comment by borkdude** [comment]
@genmeblog I liked the idea though. Some people may not be aware that you can have a CLJS repl for this project. So welcome to add something to the README. Maybe there's a CIDER page where this is documented?

**Comment by genmeblog** [comment]
Yes! That could be helpful. Config was taken from Cider page. I'll prepare separate PR with information about this.

**Pull request merged**
