### PR TITLE
2018/09/iamdrowsy

### PR DESCRIPTION
**Pull request by IamDrowsy**

### CODE REVIEW

**Comment by mfikes** [comment]
This PR appears to have actually failed in CI (exhausting Node's memory), even though not marked as such.

**Comment by borkdude** [comment]
@mfikes Do you have an idea why this doesn't return a non-zero exit code?

**Comment by IamDrowsy** [comment]
Still blowing the stack on clojurescript :(

**Comment by mfikes** [comment]
It may not be this particular PR doing it. See https://github.com/borkdude/advent-of-cljc/pull/77#issuecomment-445571895

You could check by running the test by itself _vs._ with all tests.

**Pull request closed without merging**
