### PR TITLE
2018/04/mrmcc3

### PR DESCRIPTION
**Pull request by mrmcc3**

### CODE REVIEW

**Comment by borkdude** [comment]
@mrmcc3 Can't accept this solution yet, as you're doing work outside the tests:
https://github.com/borkdude/advent-of-cljc/pull/31/files#diff-bce17d95fed9d4f1252dde5ebde0a5b3R29
Please change. See README.

**Comment by mrmcc3** [comment]
there is a sneaky delay at the end

**Comment by borkdude** [comment]
Gotcha.

**Comment by borkdude** [comment]
@mrmcc3 

I see:

```
Testing aoc.y2018.d04.mrmcc3
part-2 took 40.97 msecs
part-1 took 0.65 msecs
```

```
Testing aoc.y2018.d04.mrmcc3
part-1 took 49.00 msecs
part-2 took 10.00 msecs
```

**Comment by mrmcc3** [comment]
Ahh ok no worries

**Comment by borkdude** [comment]
@mrmcc3 I noticed this a couple of times now too. I think I fixed it by setting a JVM memory option.

**Pull request merged**
