### PR TITLE
2018/09/mfikes

### PR DESCRIPTION
**Pull request by mfikes**
Note that this PR intentionally uses the exact same input file as in the exiting PR #76.

Since the Clojure part 2 runs in 1/2 minute and ClojureScript runs in about a minute, it might make sense to comment part 2 from this submission? (Or perhaps add meta indicating that they are long-running?)

### CODE REVIEW

**Comment by mfikes** [comment]
This PR is also blowing out the heap on Node.

**Comment by borkdude** [comment]
@mfikes I would love to use metadata for this, but it seems that ClojureScript advanced compilation doesn't see this. It works with optimizations none though.

**Comment by mfikes** [comment]
When I run this by itself, it doesn't blow the stack. The code is designed to not use much memory based on its use of a transducer and `iterate`. In fact, Node memory usage remains quite low. You can also see for yourself if you cut and paste https://github.com/mfikes/advent-of-code/blob/master/src/advent_2018/day_09.cljc into Lumo or Planck.

A theory: Preceding tests are employing memoization and, by the time it gets to these tests, there is not much memory left to run things in.

An alternative theory is that somehow things are changing under advanced, but that seems unlikely given that things run fine when you run the test by itself, and also this would be a very bad advanced bug if true.

**Comment by mfikes** [comment]
OK, with the changes above, it is actually filtering under `:advanced`. This points things at a fork of the test runner for now, but a PR to the upstream test runner is here https://github.com/Olical/cljs-test-runner/pull/21

**Pull request merged**
